### ISSUE TITLE
Invoke-Mimikatz doesn't work

### ISSUE THREAD

**Issue by jaredhaight** [jaredhaight/PSPunch#2]

**Comment by jaredhaight** [comment]
Works against remote computers, just not local.
![screen shot 2016-01-31 at 2 00 12 pm](https://cloud.githubusercontent.com/assets/1220886/12704185/1ae9617c-c823-11e5-9bd5-295a119ec575.png)

Local run acts like it's not being invoked with admin rights.
![screen shot 2016-01-31 at 2 01 05 pm](https://cloud.githubusercontent.com/assets/1220886/12704189/28e61dce-c823-11e5-9139-1142841ba174.png)

Weird.

**Comment by vysec** [comment]
Perhaps needs elevated admin rights? I've not looked at Invoke-Mimikatz but perhaps it runs in an elevated context?

-ComputerName should require credentials, when it's not provided I guess it uses it's current credentials to auth to the other computer. Therefore have a look below.

`-ComputerName string[]
       The computers on which to run the command.
       The default is the local computer. 
        
       When you use -ComputerName,  PowerShell will create a temporary connection that is
       used only to run the specified command and is then closed.
       If you need a persistent connection, use -Session
        
       Type the NETBIOS name, IP address, or fully-qualified domain name of one or more computers
       in a comma-separated list. To specify the local computer, type the computer name, "localhost", or a dot (.)
        
       To use an IP address in the value of -ComputerName , the command must include -Credential.
       Also, the computer must be configured for HTTPS transport or the IP address of the remote
       computer must be included in the WinRM TrustedHosts list on the local computer.
       See also: "How to Add  a Computer to the Trusted Host List" in help about_Remote_Troubleshooting.
        
       Note: On Vista, and later, to include the local computer in the value of -ComputerName, you must
       open PowerShell with the "Run as administrator" option.`

**Comment by jaredhaight** [comment]
Yeah, that's whats weird, this is with in a console with elevated rights. Everything else behaves as expected (for example Inveigh runs properly), but for whatever reason it's like mimikatz isn't being run with the proper rights. I'm thinking it might have something to do with the reflected DLL injection that it uses.

I looked at it a bit today with no luck, I'll definitely keep at it. Any thoughts or ideas are certainly welcome.

**Comment by vysec** [comment]
Is Invoke-Mimikatz running "debug::privilege"? As I recall, this is required because I remember trying it in some scenarios where Mimikatz would not extract anything if it was not set to debug privilege.
